name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger with inputs
    inputs:
      imageToBuild:
        description: 'The image directory to build'
        required: true
        default: 'my-nodejs-app'
      tagImage:
        description: 'Tag for the image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Docker Buildx (required for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push Docker image to GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .       # this based on folder structure
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild || 'nodejs' }}:${{ github.event.inputs.tagImage || 'latest' }} # Ensure 'latest' as default if no tagImage is provided
          build-args: |
            SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 5: Send success notification to Slack if the build succeeds
      - name: Send success notification to Slack
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*${{ github.repository_owner }}*",
              "attachments": [
                {
                  "color": "good",
                  "fields": [
                    { "title": "Ref", "value": "${{ github.ref }}" },
                    { "title": "Event", "value": "${{ github.event_name }}" },
                    { "title": "Actions URL", "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" },
                    { "title": "Commit", "value": "${{ github.sha }}" },
                    { "title": "Docker image build status", "value": "Docker image is ready ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild || 'nodejs' }}:${{ github.event.inputs.tagImage || 'latest' }}" }
                  ]
                }
              ],
              "footer": "Powered By rtCamp's GitHub Actions Library | Triggered on this workflow run"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 6: Send failure notification to Slack if the build fails
      - name: Send failure notification to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*${{ github.repository_owner }}*",
              "attachments": [
                {
                  "color": "danger",
                  "fields": [
                    { "title": "Ref", "value": "${{ github.ref }}" },
                    { "title": "Event", "value": "${{ github.event_name }}" },
                    { "title": "Actions URL", "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" },
                    { "title": "Commit", "value": "${{ github.sha }}" },
                    { "title": "Docker image build status", "value": "Docker image build failed :x:" }
                  ]
                }
              ],
              "footer": "Powered By rtCamp's GitHub Actions Library | Triggered on this workflow run"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
