name: Docker Image Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      imageToBuild:
        description: 'The image directory to build'
        required: true
        default: 'my-nodejs-app'
      tagImage:
        description: 'Tag for the image'
        required: true
        default: 'latest'

jobs:
  build_and_test:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build --file ./${{ github.event.inputs.imageToBuild }}/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }} \
            ./${{ github.event.inputs.imageToBuild }}

      # Step 4: Run the Docker container for testing
      - name: Run Docker Container
        run: |
          docker run --name test-container -p 8080:80 -d \
            ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }}

      # Step 5: Install curl to test the running container
      - name: Install curl
        run: sudo apt-get install -y curl

      # Step 6: Test if the container serves data
      - name: Test: Request Data
        run: |
          sleep 5 # Allow container time to initialize
          curl -s http://localhost:8080 || (echo "Container failed to respond!" && exit 1)

      # Step 7: Verify that the Docker image does not run as root
      - name: Non-Root Access Check
        uses: wetransform/gha-docker-nonroot@v1.0.3
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }}
          fail-for-root: true

      # Step 8: Stop and remove the Docker container
      - name: Cleanup Container
        if: always()
        run: |
          docker stop test-container
          docker rm test-container

      # Step 9: Send success notification to Slack
      - name: Send success notification to Slack
        if: success()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "Docker image build notification:",
              "attachments": [
                {
                  "fallback": "Docker image built successfully: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }}",
                  "pretext": "Docker image build completed successfully! 🎉",
                  "color": "#36a64f",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }}",
                      "short": true
                    },
                    {
                      "title": "Ref",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    },
                    {
                      "title": "Actions URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 10: Send failure notification to Slack
      - name: Send failure notification to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "Docker image build notification:",
              "attachments": [
                {
                  "fallback": "Docker image build failed for: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }}",
                  "pretext": "Docker image build encountered an error! ❌",
                  "color": "#FF0000",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageToBuild }}:${{ github.event.inputs.tagImage }}",
                      "short": true
                    },
                    {
                      "title": "Ref",
                      "value": "${{ github.ref }}",
                      "short": true
                    },
                    {
                      "title": "Commit",
                      "value": "${{ github.sha }}",
                      "short": true
                    },
                    {
                      "title": "Actions URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
